DROP USER IF EXISTS webappuser;
CREATE USER 'webappuser'@'localhost' IDENTIFIED BY 'Password1!';
GRANT ALTER, SHOW VIEW, SHOW DATABASES, SELECT, PROCESS, EXECUTE, CREATE ROUTINE, CREATE, ALTER ROUTINE, CREATE VIEW, CREATE TEMPORARY TABLES, CREATE TABLESPACE, EVENT, DROP, DELETE, REFERENCES, INSERT, INDEX, CREATE USER, UPDATE, TRIGGER, LOCK TABLES, FILE, REPLICATION SLAVE, REPLICATION CLIENT, RELOAD, SUPER, SHUTDOWN  ON *.* TO 'webappuser'@'localhost' WITH GRANT OPTION;



